import Head from "next/head";
import React, { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { Link, animateScroll as scroll } from "react-scroll";

export default function Home({}) {
  useEffect(() => {
    scroll.scrollToTop();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Roger Siver</title>
        <meta name="description" content="generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex-col items-center content-center flex-1"
        x-data="{details: false}"
      >
        <div className="sticky z-10 flex items-center h-screen bg-black lg:w-screen">
          <iframe
            src="https://my.spline.design/floppydiskcopy-48e877525c571964c62e09fffcf22477/"
            frameBorder="0"
            width="100%"
            height="100%"
          ></iframe>
          <p
            onClick={() => {
              scroll.scrollToBottom();
            }}
            className="absolute invisible p-2 m-40 text-3xl opacity-50 cursor-pointer transition ease-in-out hover:-translate-y-1 hover:scale-110 hover:opacity-100 duration-300 lg:visible sm:mb-20"
          >
            ↓👇
          </p>
          <p
            onClick={() => {
              scroll.scrollToBottom();
            }}
            className="absolute top-0 visible p-2 text-3xl italic rounded-lg cursor-pointer lg:invisible backdrop-blur-xl"
          >
            ↓👇
          </p>
        </div>
        <div className="sticky flex justify-center w-screen h-screen m-auto place-content-center place-items-center bg-zinc-900">
          <div className="max-w-3xl">
            <div className="mx-4 mt-16">
              <div className="flex mx-4 text-4xl ">
                I'm <p className="mx-2 font-bold text-green-500"> Roger</p>{" "}
                <p className="font-bold">Siver,</p>
              </div>
              <img
                className="float-right rounded-full "
                src="https://avatars.githubusercontent.com/u/21316328?v=4"
                width="150px"
              />

              <p className="float-none mx-4 mt-4 mb-4 text-base leading-relaxed ">
                I'm a full stack web developer, software engineer, motion
                graphic designer, and event industry AV Tech/Production Manager.
                I come up with complete solutions for tough problems and deliver
                bespoke customer experiences. From lightshows & creative visuals
                to websites and full-stack software, I can definitely help.
              </p>
            </div>
            <div className="mx-6 grid gap-5 sm:grid-cols-1 lg:grid-cols-3 place-items-center">
              <div className="w-full px-6 bg-zinc-700 rounded-2xl">
                <a
                  href="http://github.com/rogersiver"
                  target="_blank"
                  className="cursor-pointer card"
                >
                  <h2 className="font-bold">Github</h2>
                  <p>
                    My dotfiles, coding bootcamp projects, personal projects &
                    explosive recipes
                  </p>
                </a>
              </div>
              <div className="w-full px-6 m-2 bg-zinc-700 rounded-2xl">
                <a
                  href="https://www.linkedin.com/in/roger-siver/"
                  target="_blank"
                  className="cursor-pointer card"
                >
                  <h2>LinkedIn</h2>
                  <p>
                    Share nudes and meet dates with me on the absolute correct
                    platform{" "}
                  </p>
                </a>
              </div>
              <div className="w-full px-6 bg-zinc-700 rounded-2xl">
                <a
                  href="https://www.linkedin.com/in/roger-siver/"
                  target="_blank"
                  className="cursor-pointer card"
                >
                  <h2>CV</h2>
                  <p>
                    Make fun of my lack of experience and "gaps in work" with
                    your co-workers
                  </p>
                </a>
              </div>
              <p
                onClick={() => {
                  scroll.scrollToTop();
                }}
                className="absolute right-0 invisible p-2 m-40 text-3xl italic opacity-50 cursor-pointer transition ease-in-out hover:-translate-y-1 hover:scale-110 hover:opacity-100 duration-300 lg:visible "
              >
                ☝️
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
