import Head from 'next/head';
import React, { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import { Link, animateScroll as scroll } from 'react-scroll';

export default function Home({ })
{
  // useEffect(() =>
  // {
  //   scroll.scrollToTop();
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Roger Siver</title>
        <meta name='description' content='generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main
        className='flex-col content-center flex-1 items-center'
        x-data='{details: false}'
      >
        <div className=' bg-black sticky h-screen lg:w-screen flex items-center z-10'>
          <iframe
            src='https://my.spline.design/floppydiskcopy-48e877525c571964c62e09fffcf22477/'
            frameBorder='0'
            width='100%'
            height='100%'
          ></iframe>
          <p
            onClick={() =>
            {
              scroll.scrollToBottom();
            }}
            className='transition ease-in-out hover:-translate-y-1 hover:scale-110 hover:opacity-100 duration-300 invisible lg:visible opacity-50 cursor-pointer text-3xl m-40 sm:mb-20 absolute p-2'
          >
            👇
          </p>
          <p
            onClick={() =>
            {
              scroll.scrollToBottom();
            }}
            className='visible lg:invisible cursor-pointer text-3xl italic top-0 absolute backdrop-blur-xl p-2 rounded-lg'
          >
            👇
          </p>
        </div>
        <div className='flex sticky place-content-center place-items-center justify-center bg-zinc-900 m-auto h-screen w-screen'>
          <div className='max-w-3xl'>
            <div className='mx-4 mt-20'>
              <div className='flex text-4xl mx-4 '>
                I'm <p className='text-green-500 mx-2 font-bold'> Roger</p>{' '}
                <p className='font-bold'>Siver,</p>
              </div>
              <img
                className=' float-right rounded-full'
                src='https://avatars.githubusercontent.com/u/21316328?v=4'
                width='150px'
              />

              <p className=' float-none text-base leading-relaxed mt-4 mx-4 mb-4 '>
                I'm a full stack web developer, software engineer, motion
                graphic designer, and event industry AV Tech/Production Manager.
                I come up with complete solutions for tough problems and deliver
                bespoke customer experiences. From lightshows & creative visuals
                to websites and full-stack software, I can definitely help.
              </p>
            </div>
            <div className='grid gap-5 sm:grid-cols-1 lg:grid-cols-3 place-items-center mx-6'>
              <div className='w-full px-6 bg-zinc-700 rounded-2xl'>
                <a
                  href='http://github.com/rogersiver'
                  target='_blank'
                  className='card cursor-pointer'
                >
                  <h2 className='font-bold'>Github</h2>
                  <p>
                    My dotfiles, coding bootcamp projects, personal projects &
                    explosive recipes
                  </p>
                </a>
              </div>
              <div className='w-full m-2 px-6 bg-zinc-700 rounded-2xl'>
                <a
                  href='https://www.linkedin.com/in/roger-siver/'
                  target='_blank'
                  className='card cursor-pointer'
                >
                  <h2>LinkedIn</h2>
                  <p>
                    Share nudes and meet dates with me on the absolute correct
                    platform{' '}
                  </p>
                </a>
              </div>
              <div className='w-full px-6 bg-zinc-700 rounded-2xl'>
                <a
                  href='https://www.linkedin.com/in/roger-siver/'
                  target='_blank'
                  className='card cursor-pointer'
                >
                  <h2>CV</h2>
                  <p>
                    Make fun of my lack of experience and "gaps in work" with
                    your co-workers
                  </p>
                </a>
              </div>
              <p
                onClick={() =>
                {
                  scroll.scrollToTop();
                }}
                className='transition ease-in-out hover:-translate-y-1 hover:scale-110 opacity-50 hover:opacity-100 duration-300 invisible lg:visible cursor-pointer text-3xl italic right-0 m-40 absolute p-2 '
              >
                ☝️
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
